### ISSUE TITLE
 1

### ISSUE THREAD

**Issue by conan7456** [LAMDA-NJU/Deep-Forest#11]

**Comment by xuyxu** [comment]
Hi, I have read the latest comment on that webpage:

**(1) Large costs on memory and training time**
We are deeply aware that this is a problem that greatly limits the use of deep forest in many scenarios. This package has made many efforts on making it more time and memory efficient. You can check the [experiments](http://www.lamda.nju.edu.cn/deep-forest/experiments.html). On HIGGS dataset (a benchmark tabular dataset with millions of samples), it took roughly 2 hours to train and evaluate a deep forest, and the running memory is approximately 16GB if you are using the `partial_mode`, which should be acceptable for most people.

**(2) GPU support**
We have tried the GPU tree from XGBoost, but the result is not satisfactory, possibly because it is optimized for GBDT, where using decision tree with a small depth is enough. Currently, we are working on a version that implements the decision tree via [CuPy](https://docs.cupy.dev/en/stable/index.html).

**(3) The effect of cascade layer**
The number of cascade layers is automatically determined by the model. You can check logs in the [Repo](https://github.com/xuyxu/deep_forest_benchmarks) that reproduces all experiments. On tabular datasets, which is friendly to deep forest, the number of cascade layers typically is smaller than 5. On image datasets, which can be hard for all tree-based methods, deep forest will grow more than 10 cascade layers.
