### ISSUE TITLE
pip install deep-forest didn't work in python3.10

### ISSUE THREAD

**Issue by buliugu** [LAMDA-NJU/Deep-Forest#120]
ERROR: Could not find a version that satisfies the requirement deep-forest (from versions: none)
ERROR: No matching distribution found for deep-forest

**Comment by xuyxu** [comment]
Hi @buliugu, please provide more information on your running system.

**Comment by buliugu** [comment]
![image](https://user-images.githubusercontent.com/3390134/207282606-ea83d513-883d-4e0e-bc9c-8584f8be256a.png)
os：win10
python:3.10.4

**Comment by xuyxu** [comment]
python3.10 is not supported yet, please consider to downgrade it to 3.9, or use a virtual environment.

**Comment by simonprovost** [comment]
> ![image](https://user-images.githubusercontent.com/3390134/207282606-ea83d513-883d-4e0e-bc9c-8584f8be256a.png) os：win10 python:3.10.4

We've opened a community fork of `Deep Forest` to support `Python 3.10+` 🥳 mainly due to the fact that current maintainers are either on other avenues of research or too slowly maintaining the project for years; [it has kindly been tried to support 3.10+](https://github.com/LAMDA-NJU/Deep-Forest/pull/155) _back in September 2025_ [but with CI and CD failing ](https://github.com/LAMDA-NJU/Deep-Forest/actions/runs/17707533516) we decided to go ahead on a side-gig while making sure to acknowledge the primary authors’ amazing work on Deep Forest!

> [!NOTE]
> _PS: We made sure to mention that if a pull request is welcomed and that it will be treated as high priority we are more than welcome to do that and remove the community fork, but we've waited too long._

**Repo**: https://github.com/simonprovost/deep_forest_py310
**PyPI**: https://pypi.org/project/deep-forest-py310/

Cheers!
