### ISSUE TITLE
pip install doesn't work

### ISSUE THREAD

**Issue by Alberto199810** [LAMDA-NJU/Deep-Forest#127]
when running "pip install deep-forest"
i keep on receiving:
"""
ERROR: Could not find a version that satisfies the requirement deep-forest (from versions: none)
ERROR: No matching distribution found for deep-forest
"""

can you solve this issue?

**Comment by xuyxu** [comment]
Hi @Alberto199810, please provide more information on your running system.

**Comment by Alberto199810** [comment]
Hu @xuyxu, I'm running Python 3.11.1 on Windows 10.0.19044 with Intel Core i7-1265U. Hope this helps.

**Comment by xuyxu** [comment]
Python 3.11 is currently not supported. Please consider to create a virtual environment with Python 3.9 and try pip install after then.

**Comment by Alberto199810** [comment]
Thanks so much for the help!

**Comment by simonprovost** [comment]
> Hu [@xuyxu](https://github.com/xuyxu), I'm running Python 3.11.1 on Windows 10.0.19044 with Intel Core i7-1265U. Hope this helps.

We've opened a community fork of `Deep Forest` to support `Python 3.10+` 🥳 mainly due to the fact that current maintainers are either on other avenues of research or too slowly maintaining the project for years; [it has kindly been tried to support 3.10+](https://github.com/LAMDA-NJU/Deep-Forest/pull/155) _back in September 2025_ [but with CI and CD failing ](https://github.com/LAMDA-NJU/Deep-Forest/actions/runs/17707533516) we decided to go ahead on a side-gig while making sure to acknowledge the primary authors’ amazing work on Deep Forest!

> [!NOTE]
> _PS: We made sure to mention that if a pull request is welcomed and that it will be treated as high priority we are more than welcome to do that and remove the community fork, but we've waited too long._

**Repo**: https://github.com/simonprovost/deep_forest_py310
**PyPI**: https://pypi.org/project/deep-forest-py310/

Cheers!
