### ISSUE TITLE
Is it possible to use FPGA acceleration?

### ISSUE THREAD

**Issue by NullLimite** [LAMDA-NJU/Deep-Forest#72]

**Comment by xuyxu** [comment]
Hi @NullLimite, this should be possible since FPGA acceleration on random forests has been extensively studied in the literature. However, hardware-level acceleration is clearly beyond the development purpose of this package.

We are happy to have your work posted [here](https://deep-forest.readthedocs.io/en/latest/report_from_users.html) if U are going to work on this.
